### ISSUE TITLE
Documentation of changes to model code

### ISSUE THREAD

**Issue by suku248** [jakobj/nest-simulator#72]
5g introduces a few changes to model code. In order to help users and developers to update their custom models to NEST 2.16, the necessary changes to neuron models, synapse models, and devices need to be documented.

@heplesser suggested to create an entry on the website similar to the documentation of [the conversion of models from 3g to 4g](http://nest.github.io/nest-simulator/model_conversion_3g_4g).

**Comment by jakobj** [comment]
# Updating models from 2.14 or prior to 2.16

With the introduction of the new connection infrastructure of the 5g kernel (https://www.frontiersin.org/articles/10.3389/fninf.2018.00002/full), neuron, synapse and device models need to be slightly adapted from prior versions to be compatible with the latest release (2.16).
The following describes all necessary changes. If you still encounter issues after following these instructions, please contact the NEST User mailing list (http://mail.nest-initiative.org/cgi-bin/mailman/listinfo/nest_user), create an issue on GitHub (https://github.com/nest/nest-simulator/issues), or directly submitting a pull request, updating these instructions.

## Converting neuron models
Since events are now delivered in the same timestep as they are communicated, there is no need to correct for the min-delay duration in the `handle` functions of rate neurons.
Remove `- kernel().connection_manager.get_min_delay()` in the `handle(...)` functions of rate neurons.

## Converting synapse models
The time of the last spike going through a particular connection (`t_lastspike`) now stored directly in the corresponding synapse objects.
Remove the `t_lastspike` argument from the `check_connection` and `send` functions of connections and add a new private member `t_lastspike` for connections requiring spike-timing information.
Make sure to initialize this new variable in the constructor and set it to the spike time (typically `t_spike`) at the end of `send(...)`.

All connections transmitting secondary events now need to tell the ModelManager whether they support waveform relaxation when registering the model.
Make sure to add the corresponding argument in `register_secondary_connection_model` (see modelsmodule.cpp, e.g., `gap_junction`).

## Converting devices
All devices are now subclasses of new class `DeviceNode` which takes care of additional infrastructure information.
In all devices models, include `device_node.h` instead of `node.h` and replace all `Node` with `DeviceNode`.

**Comment by jakobj** [comment]
what do you think @suku248 @heplesser @jessica-mitchell ?

**Comment by heplesser** [comment]
@jakobj Quite fine, but I think it would be even better with one "before-and-after" example directly in the text.

Also, in the first paragraph "directly submitting" -> "directly submit".

**Comment by jakobj** [comment]
do you mean a before and after example for each of the changes metioned above. how about a diff instead? because there are so few changes, just before and after won't help users a lot, would it?

**Comment by heplesser** [comment]
A diff would probably be good, and people writing their own NEST models should be able to read diffs.

**Comment by jessica-mitchell** [comment]
I also think this looks pretty good and agree it should have some sort of example.
I just have a couple of questions and notes:
Where is this information planning on being located (in which directory on Github?) and how will people find it? 
In my opinion, I think we should include a link on the website (the old one for now) and the developer space.
Please add the verb indicated in bold to the sentence: "The time of the last spike going through a particular connection (t_lastspike) **is** now stored directly . . ."
Please add an article: "All devices are now subclasses of **a/the** new class . . ."

**Comment by jakobj** [comment]
ok, i've added diff for examples. the information will probably be located at the same location as the previous instructions on how to update models and a link should be included in the release notes. we can also place a prominent link on the website to allow users to find it more easily.

**Comment by heplesser** [comment]
@jakobj Thanks! Could you change the header "Converting neuron models" to "Converting rate neuron models" and also make i very clear in the text that this applies only to rate neuron models, not spiking models---I had gotten very confused there yesterday.

**Comment by jakobj** [comment]
ok, updated. FYI, for spiking models we're taking care of assigning the correct time stamps already in the `prepared_timestamps` (https://github.com/jakobj/nest-simulator/blob/5g/nestkernel/event_delivery_manager.cpp#L663)

**Comment by jakobj** [comment]
asked @steffengraber to move the description to the developer space. closing.
