### ISSUE TITLE
Test all examples with 5G

### ISSUE THREAD

**Issue by heplesser** [jakobj/nest-simulator#73]
All examples need to be run with 5G

**Comment by stinebuu** [comment]
I am not able to run the `conngen_interface.sli` example, but I am not able to run it on master either, so it is not a 5g problem. It has to do with the fact that I do not have `libcsa.so`. Maybe this is connected to the C++ version of CSA? I have a `libpycsa.so`, but I am not able to make it work with this, I get a `not registered library` message. I am able to get all PyNEST CSA examples and tests to run, so I don't think it has to do with my CSA and libneurosim installation. Maybe @jougs can try to run the example when he is back?

All PyNEST examples except `pynest/examples/correlospinmatrix_detector_two_neuron.py ` run with 5g, see #75 for the problem with said example. There are some examples in master that have been added after merging master into the 5g branch, so those obviously have to be checked at some point. Those are

- `brunel_alpha_evolution_strategies.py`
- `gif_pop_psc_exp.py`
- `hpc_benchmark.py`

All PyNEST examples give results that are comparable with master, with some differences due to randomness. So the inhibitory rate for `brunel_alpha_nest.py` in master is 28.40 Hz, while it is 28.44 Hz in 5g. `cross_check_mip_corrdet.py` has the biggest differences, but the numbers here are bigger, so maybe it is still within the margin of error. The example uses the `mip_generator`, which uses randomization, so some difference is to be expected. The sum of cross correlation in master is 4954032.0, while it is 4953001.0 in 5g.

**Comment by stinebuu** [comment]
I have now discussed this with @suku248 and @heplesser, and we think the difference between master and 5g for the PyNEST examples stems from a difference in when spikes are registered in 5g and master. The spikes in the last time step is not recorded in master, but they are in 5g, so this is where the difference occurs. If I stop recording spikes before the simulation ends, the rate is the same for both master and 5g for the `brunel_alpha_nest.py` example. The `local_spike_counter` is different for master and 5g, but this is probably because 5g record the spikes from the last time step. 5g have a higher `local_spike_counter` count than master for both `brunel_alpha_nest.py` and `hbc_benchmark.py`, which supports this theory.

**Comment by stinebuu** [comment]
I have run `brunel_alpha_evolution_strategies.py` and `hpc_benchmark.py` with 5g now. These have the same differences as above. I can't run the `gif_pop_psc_exp.py` example with 5g, because it uses the `gif_pop_psc_exp` model, which is not yet in 5g.

**Comment by heplesser** [comment]
@stinebuu Thanks for checking! Is `gif_pop_psc_exp` not yet in 5G because it simply has not been merge from master yet, or are there deeper reasons?

**Comment by stinebuu** [comment]
@heplesser It simply has not been merged with master yet. :)

**Comment by hakonsbm** [comment]
I have tested `gif_pop_psc_exp.py` now, and it gives results identical with master.

**Comment by heplesser** [comment]
@stinebuu @hakonsbm Thanks for testing. It then seems that all examples work properly with 5G, thus closing.
